<?php

namespace App\Exceptions;

use Illuminate\Database\Eloquent\ModelNotFoundException;
use Illuminate\Foundation\Exceptions\Handler as ExceptionHandler;
use Illuminate\Http\Client\RequestException;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Validation\ValidationException;
use Symfony\Component\HttpKernel\Exception\HttpException;
use Symfony\Component\Routing\Exception\RouteNotFoundException;
use Illuminate\Support\Facades\Log;
use Throwable;

class Handler extends ExceptionHandler
{
    /**
     * A list of the exception types that are not reported.
     *
     * @var array
     */
    protected $dontReport = [
        //
    ];

    /**
     * A list of the inputs that are never flashed for validation exceptions.
     *
     * @var array
     */
    protected $dontFlash = [
        'current_password',
        'password',
        'password_confirmation',
    ];

    /**
     * Register the exception handling callbacks for the application.
     *
     * @return void
     */
    public function register()
    {
        $this->reportable(function (Throwable $e) {
            Log::error("Unhandled Exception: " . $e->getMessage() . " in " . $e->getFile() . ":" . $e->getLine());
            //
        });
    }

    /**
     * @param Request $request
     * @param Throwable $e
     * @return JsonResponse|Response|\Symfony\Component\HttpFoundation\Response
     * @throws Throwable
     * User: zxw
     * Date: 2021/9/14 13:15
     */
    public function render($request, Throwable $e)
    {
        if ($e instanceof ModelNotFoundException) {//模型异常抛出
            return response()->json(['code' => $e->getCode(),'msg' => 'Entry for ' . str_replace('App\\', '', $e->getModel()) . ' not found']);
        } elseif ($e instanceof RequestException) {//请求异常抛出
            return response()->json(['code' => $e->getCode(),'msg' => 'External API call failed.']);
        } elseif ($e instanceof ValidationException) {//字段验证
            return response()->json(['code' => $e->getCode(),'msg' => $e->validator->errors()->first()]);
        } elseif ($e instanceof BusinessException) {//异常抛出
            return response()->json(['code' => $e->getCode(),'msg' => $e->getMessage()]);
        } elseif ($e instanceof RouteNotFoundException) {
            return response()->json(['code' => $e->getCode(),'msg' => $e->getMessage()]);
        } elseif ($e instanceof HttpException) {
            return response()->json(['code' => $e->getCode(),'msg' => $e->getMessage()]);
        }

        return parent::render($request, $e); // TODO: Change the autogenerated stub
    }
}
